// The genre options are fixed. There are no other genre possibilities.

export const genreOptions = [
    <option key={"Afrobeat"} id="Afrobeat" value="Afrobeat">Afrobeat</option>,
    <option key={"Afropop"} id="Afropop" value="Afropop">Afropop</option>,
    <option key={"Alternative"} id="Alternative" value="Alternative">Alternative</option>,
    <option key={"Bigband"} id="Bigband" value="Bigband">Bigband</option>,
    <option key={"Blues"} id="Blues" value="Blues">Blues</option>,
    <option key={"Classical"} id="Classical" value="Classical">Classical</option>,
    <option key={"Comedy"} id="Comedy" value="Comedy">Comedy</option>,
    <option key={"Country"} id="Country" value="Country">Country</option>,
    <option key={"Dance"} id="Dance" value="Dance">Dance</option>,
    <option key={"Electronic"} id="Electronic" value="Electronic">Electronic</option>,
    <option key={"Folk"} id="Folk" value="Folk">Folk</option>,
    <option key={"Hiphop/Rap"} id="Hiphop/Rap" value="Hiphop/Rap">Hiphop/Rap</option>,
    <option key={"J-Pop"} id="J-Pop" value="J-Pop">J-Pop</option>,
    <option key={"Jazz"} id="Jazz" value="Jazz">Jazz</option>,
    <option key={"K-Pop"} id="K-Pop" value="K-Pop">K-Pop</option>,
    <option key={"Latin"} id="Latin" value="Latin">Latin</option>,
    <option key={"Metal"} id="Metal" value="Metal">Metal</option>,
    <option key={"New Age"} id="New Age" value="New Age">New Age</option>,
    <option key={"Pop"} id="Pop" value="Pop">Pop</option>,
    <option key={"Punk"} id="Punk" value="Punk">Punk</option>,
    <option key={"Reggae"} id="Reggae" value="Reggae">Reggae</option>,
    <option key={"Rock"} id="Rock" value="Rock">Rock</option>,
    <option key={"Singer-songwriter"} id="Singer-songwriter" value="Singer-songwriter">Singer-songwriter</option>,
    <option key={"Soundtrack"} id="Soundtrack" value="Soundtrack">Soundtrack</option>]